import type { PatternShape, PresetName, PresetParams } from './types';

export const PatternShapes: Record<PatternShape, number> = {
  Checks: 0,
  Stripes: 1,
  Edge: 2,
};

export const animatedGradientPresets: Record<PresetName, PresetParams> = {
  Prism: {
    color1: '#050505',
    color2: '#66B3FF',
    color3: '#FFFFFF',
    lightColors: {
      color1: '#FAFAFA',
      color2: '#66B3FF',
      color3: '#050505',
    },
    rotation: -50,
    proportion: 1,
    scale: 0.01,
    speed: 30,
    distortion: 0,
    swirl: 50,
    swirlIterations: 16,
    softness: 47,
    offset: -299,
    shape: 'Checks',
    shapeSize: 45,
  },
  Lava: {
    color1: '#FF9F21',
    color2: '#FF0303',
    color3: '#000000',
    lightColors: {
      color1: '#FF9F21',
      color2: '#FF0303',
      color3: '#FAFAFA',
    },
    rotation: 114,
    proportion: 100,
    scale: 0.52,
    speed: 30,
    distortion: 7,
    swirl: 18,
    swirlIterations: 20,
    softness: 100,
    offset: 717,
    shape: 'Edge',
    shapeSize: 12,
  },
  Plasma: {
    color1: '#B566FF',
    color2: '#000000',
    color3: '#000000',
    lightColors: {
      color1: '#B566FF',
      color2: '#FAFAFA',
      color3: '#FAFAFA',
    },
    rotation: 0,
    proportion: 63,
    scale: 0.75,
    speed: 30,
    distortion: 5,
    swirl: 61,
    swirlIterations: 5,
    softness: 100,
    offset: -168,
    shape: 'Checks',
    shapeSize: 28,
  },
  Pulse: {
    color1: '#66FF85',
    color2: '#000000',
    color3: '#000000',
    lightColors: {
      color1: '#66FF85',
      color2: '#FAFAFA',
      color3: '#FAFAFA',
    },
    rotation: -167,
    proportion: 92,
    scale: 0,
    speed: 20,
    distortion: 54,
    swirl: 75,
    swirlIterations: 3,
    softness: 28,
    offset: -813,
    shape: 'Checks',
    shapeSize: 79,
  },
  Vortex: {
    color1: '#000000',
    color2: '#FFFFFF',
    color3: '#000000',
    lightColors: {
      color1: '#FAFAFA',
      color2: '#000000',
      color3: '#FAFAFA',
    },
    rotation: 50,
    proportion: 41,
    scale: 0.4,
    speed: 20,
    distortion: 0,
    swirl: 100,
    swirlIterations: 3,
    softness: 5,
    offset: -744,
    shape: 'Stripes',
    shapeSize: 80,
  },
  Mist: {
    color1: '#050505',
    color2: '#FF66B8',
    color3: '#050505',
    lightColors: {
      color1: '#FAFAFA',
      color2: '#FF66B8',
      color3: '#FAFAFA',
    },
    rotation: 0,
    proportion: 33,
    scale: 0.48,
    speed: 39,
    distortion: 4,
    swirl: 65,
    swirlIterations: 5,
    softness: 100,
    offset: -235,
    shape: 'Edge',
    shapeSize: 48,
  },
};

export const presetNames: PresetName[] = ['Prism', 'Lava', 'Plasma', 'Pulse', 'Vortex', 'Mist'];
export const patternShapes: PatternShape[] = ['Checks', 'Stripes', 'Edge'];
